# Generated by Django 6.0.5 on 2026-05-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=20)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor')),
            ],
        ),
    ]
