# Generated by Django 6.0.5 on 2026-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='es_base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.CharField(default='SIN_GRUPO', max_length=20),
            preserve_default=False,
        ),
    ]
