# Generated by Django 6.0.5 on 2026-05-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_horario_es_base_horario_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('grupo', models.CharField(max_length=20)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_novedad', models.CharField(choices=[('cambio_clase', 'Cambio de Clase'), ('cambio_profesor', 'Cambio de Profesor'), ('cambio_salon', 'Cambio de Salón'), ('no_asiste', 'No Asiste/Grupo Ausente'), ('suspendida', 'Clase Suspendida'), ('otra', 'Otra Novedad')], max_length=50)),
                ('salon_original', models.CharField(blank=True, max_length=20, null=True)),
                ('salon_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('materia_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_nueva', to='usuarios.materia')),
                ('materia_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_original', to='usuarios.materia')),
                ('profesor_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_nueva', to='usuarios.profesor')),
                ('profesor_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_original', to='usuarios.profesor')),
            ],
            options={
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha', 'grupo'],
            },
        ),
    ]
