# Generated by Django 6.0.5 on 2026-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilcoordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
